version: '3'

services:

  # -----------------------------------------
  # KEYCLOAK
  # -----------------------------------------
  keycloak:
    image: "jboss/keycloak"
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - "8080:8080"